### ISSUE TITLE
Improve the static site

### ISSUE THREAD

**Issue by ianpurton** [purton-tech/bionicgpt#55]
- [x] Choose a template for the docs
- [x] Choose a template for the blog
- [x] Get something for the site pages i.e. /, /pricing, /etc
- [x] Home page on mobile
- [x] Use dioxus to generate pages?
- [x] Hook into zola to parse front matter etc.
- [x] Fix the book menu issue
- [x] Fix the book side menu to keep scroll position.

Medium Samples

- https://blog.base68.com/mediator/feature/2014/11/30/mediator_features.html
- https://wowthemesnet.github.io/mediumish-theme-jekyll/quick-start-guide/
- https://wowthemesnet.github.io/mundana-theme-jekyll/welcome-to-jekyll/

Book Themes

- https://github.com/getzola/book
- https://rust-lang.github.io/mdBook/

## Todo

- [x] Split the website into zola and mdbooks
- [x] Generate docs with mdbooks
- [x] Some how combine the 2.
