### ISSUE TITLE
Store/retrieve document meta data

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/bionicgpt#63]
Store meta data with chunks in DB, document name, page number

When questions for RAG are answered allow user to see the original source/provide details of the original source

**Comment by ianpurton** [comment]
Ustructured does support meta data with filename, filetype, page number.

- [ ] Store meta data along with chunks.
- [ ] Rename embeddings to chunks?
- [ ] When using a chunk in the chat, store a reference to the chunk. chats_chunks?
- [ ] When showing the prompt, return a list of chunks that were used.

**Comment by eyalspier** [comment]
+1 here - it would be great if we could get a clickable  link to the sources for a particular piece of information. I like how Secure AI Tools implemented this: https://www.youtube.com/watch?v=Br2D3G9O47s
